Repository rezoo/movis, pull requests merged in 2023-12, with the labels that each got.

#46 Fix a bug where text layer is not clipped according to color
  movis/layer/drawing.py
Labels: bug

#45 Support for subtitle position when writing .ass file
  movis/subtitle.py
Labels: bug

#49 Use Ascii Art in the docs of mv.ops.insert()
  movis/ops.py
Labels: bug, documentation

#43 Replace movis.ops with functions without Composition
  movis/ops.py
  tests/test_ops.py
Labels: enhancement

#51 Update README.md to support recent movis
  README.md
  docs/overview.rst
Labels: documentation

#52 Update mv.repeat() to use _RepeatLayer
  movis/ops.py
  tests/test_ops.py
Labels: enhancement

#53 Update the section of Main Features
  README.md
Labels: documentation

#54 Fix the section of Main Features
  README.md
Labels: documentation

#55 Speedup mv.crop()
  movis/ops.py
  tests/test_ops.py
Labels: enhancement
